### ISSUE TITLE
question: Mi Home Security Camera 360° 720p

### ISSUE THREAD

**Issue by rchovan** [JMacalinao/mijia360-1g-hack#1]
Hi, 
is this firmware hack compatible with 720p camera ? 

Name: Mi Home Security Camera 360°
Model: MJSXJ01CM
Datasheet: https://files.xiaomi-mi.com/files/mijia_smart_camera_360/MiJia_360%C2%B0_Smart_Home_PTZ_Camera_EN.pdf

**Comment by JMacalinao** [comment]
Nope, this hack is for the first-gen 1080p version (JTSXJ01CM).

The hack for your camera is likely this one from @ghoost82: https://github.com/ghoost82/mijia-720p-hack
