### ISSUE TITLE
Could somebody help me? 

### ISSUE THREAD

**Issue by Peter71131** [JMacalinao/mijia360-1g-hack#3]
I copyed the Datas to SD-Card, Did the camera Reset, did the setup in the config for my wifi.
Seems in the log, there are some datas missing in etc for wifi?

### Mijia 360 Camera (1st-gen) Hack

----- Export variables from /sdcard/config.ini
export MCH_HACK_LANGUAGE=EN
export MCH_HACK_LANGUAGE_TRACES=true
export MCH_TIMEZONE=PHT-8
export MCH_NTP_SERVER=pool.ntp.org
export MCH_ENABLE_LED=true
export MCH_ENABLE_CLOUD=false
export MCH_ENABLE_TELNET=true
export MCH_ENABLE_SSH=true
export MCH_ENABLE_FTP=true
export MCH_ENABLE_RTSP=true
export MCH_ENABLE_HTTPD=true
export MCH_ENABLE_NIGHT_VISION=auto

----- Configure timezone
----- Setting root password
Changing password for root
New password: 
Retype password: 
Password for root changed by root
----- Creating Wi-Fi config for setup
mount: mounting /tmp/mch/wifi.conf on /etc/miio/wifi.conf failed: No such file or directory
----- Starting FTP server
tcpsvd: info: listening on 0.0.0.0:21, starting.
----- Starting SSH server

**Comment by Peter71131** [comment]
@JMacalinao At_ALL seems Ranger got it also. Has somebody some suggenstions, out of the logs what i did't wrong.

**Comment by RangerFX4** [comment]
try to deactivate SSH to before I could not access it when the SSH Server is running.

**Comment by Peter71131** [comment]
Log File looks a litte better, but i still get no IP address and successful connection. But the blue indecator light is solid on.
On my router i also could not find a connected cam.
Any Ideas?


### Mijia 360 Camera (1st-gen) Hack

----- Export variables from /sdcard/config.ini
export MCH_HACK_LANGUAGE=EN
export MCH_HACK_LANGUAGE_TRACES=true
export MCH_TIMEZONE=PHT-8
export MCH_NTP_SERVER=pool.ntp.org
export MCH_ENABLE_LED=true
export MCH_ENABLE_CLOUD=false
export MCH_ENABLE_TELNET=false
export MCH_ENABLE_SSH=false
export MCH_ENABLE_FTP=true
export MCH_ENABLE_RTSP=true
export MCH_ENABLE_HTTPD=true
export MCH_ENABLE_NIGHT_VISION=auto

----- Configure timezone
----- Setting root password
Changing password for root
New password: 
Retype password: 
Password for root changed by root
----- Creating Wi-Fi config for setup
mount: mounting /tmp/mch/wifi.conf on /etc/miio/wifi.conf failed: No such file or directory
----- Telnet enabled by default, stopping service
----- Starting FTP server
tcpsvd: info: listening on 0.0.0.0:21, starting.
----- Creating modified run script (to make stuff work)

### Modified startup (miio_modified.sh)
----- Disable timer
Removed symlink /etc/systemd/system/multi-user.target.wants/imi.timer.
----- Initializing LED
----- Configuring network (LED green flash)
----- Setting MAC address to Xiaomi
MAC address now set to 28:6C:07:75:06:E5
----- WMM
PS mode: 0
WMM Params: 
	BE: AIFSN=2, CW_MAX=3 CW_MIN=2, TXOP=150
	BK: AIFSN=2, CW_MAX=3 CW_MIN=2, TXOP=150
	VI: AIFSN=2, CW_MAX=3 CW_MIN=2, TXOP=150
	VO: AIFSN=2, CW_MAX=3 CW_MIN=2, TXOP=150
----- Default DNS server
----- Connecting to Wi-Fi
----- Connection successful (LED blue flash)
----- Synchronize time
ntpd: bad address 'pool.ntp.org'
----- Starting RTSP
Stop encoding for stream 0x1 
Stop encoding for stream 0x2 
killall: test_encode: no process killed
killall: rtsp_server: no process killed
killall: test_tuning: no process killed
1920x1080 resolution is 1920x1080
1920x1080 resolution is 1920x1080
1920x1080 resolution is 1920x1080
640x360 resolution is 640x360
640x360 resolution is 640x360
640x360 resolution is 640x360
640x360 resolution is 640x360
Stop encoding for stream 0xf 
IAVIOC_S_IDLE done

Find Vin Source ov4689 it supports:
	2688x1512P	60	RGB	10bits	16:9	AUTO	rev[0]
	2560x1440P	60	RGB	10bits	16:9	AUTO	rev[0]
	2560x1440P(HDR 2x)	30	RGB	10bits	16:9	AUTO	rev[0]
	2560x1440P(HDR 3x)	25	RGB	10bits	16:9	AUTO	rev[0]
	2688x1512P	60	RGB	10bits	16:9	AUTO	rev[0]
	2688x1520P	60	RGB	10bits	16:9	AUTO	rev[0]
	2688x1520P(HDR 2x)	30	RGB	10bits	16:9	AUTO	rev[0]
	1920x1080P(HDR 2x)	30	RGB	10bits	16:9	AUTO	rev[0]
	1920x1080P(HDR 3x)	30	RGB	10bits	16:9	AUTO	rev[0]
Active src 0's mode is:
	2560x1440P	30	RGB	10bits	16:9	AUTO	rev[0]
init_vin done
enable_preview done
Play this stream using the URL "rtsp://0.0.0.0/stream1"
Play this stream using the URL "rtsp://0.0.0.0/stream2"
Play this stream using the URL "rtsp://0.0.0.0/stream3"
Play this stream using the URL "rtsp://0.0.0.0/stream4"
1080p resolution is 1920x1080
Start encoding for stream 0x1 successfully
Start encoding for stream 0x2 successfully
----- Enabling night vision mode
## Startup complete

**Comment by RangerFX4** [comment]
connect first the camera through the app to the WiFi then put the card and try again

**Comment by Peter71131** [comment]
> connect first the camera through the app to the WiFi then put the card and try again

Thanks  @RangerFX4.
It help me to get it working.

But it still was a little difficult. 

The important thing was to remove the config settings for the wifi settings. If you have SSID and Passwort in the config, it will show a blue led and the log like this and nothing is working.

> ----- Default DNS server
> ----- Connecting to Wi-Fi
> ----- Connection successful (LED blue flash)
> ----- Synchronize time

**Solution:
Wifi Settings should be done with the app, and do not setup settings in the config file.**

**Comment by paulmorabito** [comment]
That worked! Thanks.
